# **DB 생성 및 관리**

## **1.환경준비**

In [2]:
import pandas as pd
import sqlite3
from datetime import datetime

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

## **2.DB 작업**

### (1) DB 생성 및 연결

* 데이터베이스 연결
    * 폴더는 미리 생성
    * 해당 파일이 없으면 새로 생성, 있으면 연결

In [2]:
path = 'testdb.db'
conn = sqlite3.connect(path)

### (2) DB 작업 절차

* 1) 커서 활용 : 대부분의 SQL 작업 가능
    * ① 연결
    * ② 커서 선언
    * ③ 작업 : sql
    * ④ 커밋(수정작업 저장)
    * ⑤ 연결종료

* 2) pandas 함수 활용 : 주로 insert, update, delete, select, create table & insert
    * ① 연결
    * ② 작업 : pandas 함수 이용
    * ③ 연결종료

#### 1) 테이블 생성
* 테이블 생성 작업
    * DB Browser for SQLite 에서 직접 수행
    * 파이썬에서 **연결**하고, **커서**를 생성해서 작업

In [3]:
# 커서 객체 생성
cursor = conn.cursor()

# test 테이블 생성
cursor.execute('''
CREATE TABLE IF NOT EXISTS test (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    age INTEGER NOT NULL
)
''')

# 변경사항 커밋 (저장)
conn.commit()

# 연결 종료
conn.close()

#### 2) insert
* 데이터프레임에서 직접 DB로 보내기 : df.to_sql

In [4]:
# ① 연결
conn = sqlite3.connect(path)

# ② 작업 : to_sql
data = pd.DataFrame({'name': ['Alice', 'Bob', 'Charlie', 'David'], 'age': [30, 25, 35, 40]})
data.to_sql('test', conn, if_exists='append', index=False) # test 테이블이 있으면 insert, 없으면 생성

# ③ 연결 종료
conn.close()

#### 3) Select

In [5]:
# ① 연결
conn = sqlite3.connect(path)

# ② 작업 : select
df = pd.read_sql('SELECT * FROM test', conn)
display(df)

# ③ 연결 종료
conn.close()

   id     name  age
0   1    Alice   30
1   2      Bob   25
2   3  Charlie   35
3   4    David   40

#### 4) Drop

* 커서로만 작업 가능

In [4]:
path = './db/em.db'

# ① 연결
conn = sqlite3.connect(path)

# ② 커서 선언
cursor = conn.cursor()

# ③ 작업 : 테이블 삭제
cursor.execute('DROP TABLE IF EXISTS request2')

# ④ 커밋(수정작업 저장)
conn.commit()

# ⑤ 연결종료
conn.close()

## **3.관리용 DB**

### (1) DB 생성

* DB를 아래 경로와 이름으로 생성
    * project7/db/em.db

In [1]:
path = './db/em.db'
conn = sqlite3.connect(path)

NameError: name 'sqlite3' is not defined

### (2) log 테이블 생성
* 칼럼 구성

|column name | descrition | data type | comment |
|----|----|----|----|
|datetime | 요청일시 | text | yyyy-mm-dd hh:mi:ss |
|input_text | 입력text | text |  |
|input_latitude | 입력 위도 | real |  |
|input_longitude | 입력 경도 | real |  |
|em_class | 응급 등급(1~5) | integer |  |
|hospital1 | 추천병원명 | text |  |
|addr1 | 추천병원주소 | text |  |
|tel1 | 추천병원전화번호 | text |  |
|hospital2 | 추천병원명2 | text |  |
|addr2 | 추천병원주소2 | text |  |
|tel2 | 추천병원전화번호2 | text |  |
|hospital3 | 추천병원명3 | text |  |
|addr3 | 추천병원주소3 | text |  |
|tel3 | 추천병원전화번호3 | text |  |

In [16]:
conn = sqlite3.connect(path)

cursor = conn.cursor()

cursor.execute('''
CREATE TABLE IF NOT EXISTS request (
    id INTEGER PRIMARY KEY,
    datetime TEXT NOT NULL,
    input_text TEXT NOT NULL,
    input_latitude REAL NOT NULL,
    input_longitude REAL NOT NULL,
    em_class INTEGER NOT NULL,
    hospital1 TEXT,
    addr1 TEXT,
    tel1 TEXT,
    eta1 TEXT,
    dist1 INTEGER,
    fee1 INTEGER,
    hospital2 TEXT,
    addr2 TEXT,
    tel2 TEXT,
    eta2 TEXT,
    dist2 INTEGER,
    fee2 INTEGER,
    hospital3 TEXT,
    addr3 TEXT,
    tel3 TEXT,
    eta3 TEXT,
    dist3 INTEGER,
    fee3 INTEGER
)
''')

conn.commit()

conn.close()

In [12]:
conn = sqlite3.connect(path)

df = pd.read_sql("SELECT * FROM request", conn)
display(df)

conn.close()

DatabaseError: Execution failed on sql 'SELECT * FROM request': no such table: request

### (3) log 테이블 입력 함수

In [ ]:
import pandas as pd
import sqlite3
from datetime import datetime

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [ ]:
from emergency import RecommendHospital3
import json

In [ ]:
path = './'

filename = "5-1.m4a"  # 예제 파일명

map_key_path = path + 'map_key.txt'

with open(map_key_path, 'r') as file:
    map_key = json.load(file)
naver_id, naver_key = map_key['c_id'], map_key['c_key']

hospital_recommender = RecommendHospital3(filename, naver_id, naver_key, path)

In [ ]:
hospital_recommender.load_api_key()

In [ ]:
df = hospital_recommender.search_map()

In [ ]:
df

,datetime,input_text,input_latitude,input_longitude,em_class,hospital1,addr1,tel1,eta1,dist1,...,tel2,eta2,dist2,fee2,hospital3,addr3,tel3,eta3,dist3,fee3
0,2024-12-18 17:16:06,멸링공원에서 친구가 심한 가슴 통증을 느끼고 있습니다. 숨을 쉬는 것도 힘들어하고 ...,35.185745,129.076541,2,부산광역시의료원,"부산광역시 연제구 월드컵대로 359 (거제동, 1동, 5동일부)",051-507-3000,0시간 11분,2.586 KM,...,051-867-5101,0시간 10분,2.587 KM,5500원,대동병원,부산광역시 동래구 충렬대로 187 (명륜동),051-554-1233,0시간 13분,3.398 KM,5900원

In [ ]:
conn = sqlite3.connect(path)

df = pd.read_sql('SELECT * FROM request', conn)
display(df)

conn.close()

,datetime,input_text,input_latitude,input_longitude,em_class,hospital1,addr1,tel1,hospital2,addr2,tel2,hospital3,addr3,tel3
0,2024-12-18 15:41:26,신동현대아파트입니다. 제 아버지가 갑자기 가슴을 움켜주더니 의식을 잃고 바닥에 쓰러...,37.358618,127.115036,1,분당서울대학교병원,"경기도 성남시 분당구 구미로173번길 82 (구미동, 분당서울대학교병원)",031-787-2114,대진의료재단분당제생병원,경기도 성남시 분당구 서현로180번길 20 (서현동),031-779-0114,국군수도병원,경기도 성남시 분당구 새마을로177번길 81 (율동),031-725-6075

## (4) API 호출용 함수

In [1]:
import pandas as pd
import sqlite3
from emergency import RecommendHospital3ByInput

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [2]:
input_text = "교통사고가 났어요. 머리에 피가 많이 나고 있습니다."
latitude = 36.6262309
longitude = 127.4521849

hospital_recommender = RecommendHospital3ByInput(input_text, latitude, longitude)

In [3]:
df = hospital_recommender.search_map()

1~3등급 DB에 성공적으로 추가하였습니다.

In [4]:
df

[{'hospital_name': '충북대학교병원',
  'address': '충청북도 청주시 서원구 1순환로 776-0 (개신동,충북대학교병원)',
  'phone': '043-269-6114',
  'eta': '0시간 8분',
  'distance': 3.0,
  'fee': 5390},
 {'hospital_name': '의료법인송암의료재단마이크로병원',
  'address': '충청북도 청주시 흥덕구 사직대로 26 (복대동)',
  'phone': '043-265-0071',
  'eta': '0시간 4분',
  'distance': 1.561,
  'fee': 4000},
 {'hospital_name': '의료법인한마음의료재단하나병원',
  'address': '충청북도 청주시 흥덕구 2순환로 1262 (가경동)',
  'phone': '043-230-6114',
  'eta': '0시간 10분',
  'distance': 2.518,
  'fee': 5380}]

In [18]:
conn = sqlite3.connect(path)

df = pd.read_sql('SELECT * FROM request', conn)
display(df)

conn.close()

,datetime,input_text,input_latitude,input_longitude,em_class,hospital1,addr1,tel1,hospital2,addr2,tel2,hospital3,addr3,tel3
0,2024-12-18 15:41:26,신동현대아파트입니다. 제 아버지가 갑자기 가슴을 움켜주더니 의식을 잃고 바닥에 쓰러...,37.358618,127.115036,1,분당서울대학교병원,"경기도 성남시 분당구 구미로173번길 82 (구미동, 분당서울대학교병원)",031-787-2114,대진의료재단분당제생병원,경기도 성남시 분당구 서현로180번길 20 (서현동),031-779-0114,국군수도병원,경기도 성남시 분당구 새마을로177번길 81 (율동),031-725-6075